version: '3.8'

services:
  svn-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: svn-server-webui
    ports:
      - "8080:80"     # SVN via HTTP
      - "3000:5000"   # Web UI
    volumes:
      # 使用本地目录，便于备份和迁移
      - ./data/repos:/svn/repos
      - ./data/conf:/svn/conf
      - ./data/app:/app/data
    environment:
      - SVN_HOSTNAME=localhost
      - SVN_PROTOCOL=http
      - SVN_PORT=8080
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 数据已映射到本地 ./data 目录，无需定义 volumes