
services:
  svn-server:
    image: ghcr.io/yourusername/svn-server-webui:latest
    container_name: svn-server-webui
    ports:
      - "443:80"      # 使用 HTTPS（需要配置反向代理）
      - "5000:5000"   # Web UI（建议使用反向代理）
    volumes:
      - /opt/svn/data:/data  # 使用独立的数据目录
    environment:
      - ADMIN_USERNAME=svnadmin
      - ADMIN_PASSWORD=${SVN_ADMIN_PASSWORD}  # 从环境变量读取
      - NODE_ENV=production
    restart: always
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

# 使用示例：
# 1. 复制此文件为 docker-compose.yml
# 2. 设置环境变量：export SVN_ADMIN_PASSWORD='your-strong-password'
# 3. 配置反向代理（nginx/caddy）处理 HTTPS
# 4. 运行：docker-compose up -d