services:
  svn-server:
    image: rongdede/svn-server-webui:latest
    container_name: svn-server-webui
    ports:
      - "80:80"       # SVN via HTTP
      - "3000:5000"   # Web UI (改用3000端口避免与AirPlay冲突)
    volumes:
      # 只需映射一个目录，简化使用
      - ./data:/data
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 数据已映射到本地 ./data 目录，无需定义 volumes