version: '3.8'

services:
  svn-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: svn-server-webui
    ports:
      - "8080:80"     # SVN via HTTP
      - "3000:5000"   # Web UI
    volumes:
      - svn_repos:/svn/repos
      - svn_conf:/svn/conf
      - svn_data:/app/data
    environment:
      - SVN_HOSTNAME=localhost
      - SVN_PROTOCOL=http
      - SVN_PORT=8080
      - JWT_SECRET=your-secret-key-change-this
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  svn_repos:
    name: svn_repos
  svn_conf:
    name: svn_conf
  svn_data:
    name: svn_data